#!/usr/bin/expect

# Start up the server, login, run commands, shutdown

puts "MOO test starting"

#cd "~swain/Sites/projects/lambdamoo/build"


spawn ./restart.sh LambdaCore-12Apr99
puts "sleeping for three seconds"
sleep 3
spawn /usr/local/bin/tf localhost 7777
sleep 2
expect {
    "Connection refused" { 
        send "/quit\r"
        puts "Server startup failed!"
        exit 1
    }
    "Type 'connect wizard' to log in." {
        send "connect wizard\r"        
    }
}

expect "The First Room" { puts "Success." }

sleep 2
send "@shutdown in 0 \"ending test\"\r"
expect "Do you really want to shut down the server"
send "yes\r"
expect eof
puts "Test completed successfully."
